### ISSUE TITLE
Blueprint::blob does not exist

### ISSUE THREAD

**Issue by aand18** [PKeidel/dbtolaravel#2]
Hi,
when generating migrations, it seems `blob` fields are wrongly defined with the nonexistent `blob()` method. 

Laravel uses `binary()`. See https://laravel.com/docs/master/migrations#columns 

`BadMethodCallException: Method Illuminate\Database\Schema\Blueprint::blob does not exist.`

**Comment by PKeidel** [comment]
Sorry for beeing so long quite. I now added a new feature to add some custom type mapping https://github.com/PKeidel/dbtolaravel#override-type-mapping

https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/types.html#detection-of-database-types
